import { User, Product, Order } from "../types";

export const mockUsers: User[] = [
  { id: "1", name: "Admin FarmLink", email: "admin@farmlink.ng", role: "admin" },
  { 
    id: "2", 
    name: "Alhaji Musa Danjuma", 
    email: "musa@danfarms.ng", 
    role: "farmer", 
    verified: true, 
    farmName: "Danjuma Grains & Seeds", 
    farmLocation: "Kano, Nigeria",
    trustLevel: "Platinum"
  },
  { 
    id: "3", 
    name: "Mrs. Oluchi Nwosu", 
    email: "oluchi@greenleaf.ng", 
    role: "farmer", 
    verified: true, 
    farmName: "GreenLeaf Organic Farm", 
    farmLocation: "Owerri, Imo State",
    trustLevel: "Gold"
  },
  { 
    id: "4", 
    name: "Chidi Okafor", 
    email: "chidi@buyer.ng", 
    role: "buyer" 
  },
  { 
    id: "5", 
    name: "Aisha Bello", 
    email: "aisha@kitchens.ng", 
    role: "buyer" 
  },
  { 
    id: "6", 
    name: "Segun Abraham", 
    email: "segun@poultrypros.ng", 
    role: "farmer", 
    verified: true, 
    farmName: "Segun's Poultry Empire", 
    farmLocation: "Abeokuta, Ogun State",
    trustLevel: "Silver"
  },
  { 
    id: "7", 
    name: "Dr. Ben Akpan", 
    email: "ben@aquaculture.ng", 
    role: "farmer", 
    verified: false, 
    farmName: "Akpan's Fish Dynasty", 
    farmLocation: "Uyo, Akwa Ibom",
    trustLevel: "Bronze"
  },
];

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Premium Cassava Tubers",
    category: "Crops",
    description: "Freshly harvested, high-starch cassava tubers suitable for garri or fufu production.",
    quantity: 500,
    unit: "kg",
    price: 350,
    harvestDate: "2024-03-25",
    location: "Ibadan, Oyo",
    images: ["https://storage.googleapis.com/dala-prod-public-storage/generated-images/8d322e49-9a02-4b5b-82a4-475380de7bac/cassava-tubers-dc1cf19b-1783335039606.webp"],
    deliveryOptions: ["Truck Delivery", "Farm Pickup"],
    farmerId: "3",
    farmerName: "Mrs. Oluchi Nwosu",
    farmerVerified: true,
    farmerTrustLevel: "Gold",
  },
  {
    id: "p2",
    name: "Large New Yam Tubers",
    category: "Crops",
    description: "Extra large Nigerian yams, sweet and perfect for boiling, frying or pounding.",
    quantity: 200,
    unit: "piece",
    price: 1500,
    harvestDate: "2024-03-22",
    location: "Zaki Biam, Benue",
    images: ["https://storage.googleapis.com/dala-prod-public-storage/generated-images/8d322e49-9a02-4b5b-82a4-475380de7bac/nigerian-yam-50d60748-1783335039411.webp"],
    deliveryOptions: ["Truck Delivery"],
    farmerId: "3",
    farmerName: "Mrs. Oluchi Nwosu",
    farmerVerified: true,
    farmerTrustLevel: "Gold",
  },
  {
    id: "p3",
    name: "White Maize Grains (Dry)",
    category: "Crops",
    description: "Sun-dried white maize grains, high quality, free from pests.",
    quantity: 1000,
    unit: "kg",
    price: 450,
    harvestDate: "2024-03-20",
    location: "Kano",
    images: ["https://storage.googleapis.com/dala-prod-public-storage/generated-images/8d322e49-9a02-4b5b-82a4-475380de7bac/white-maize-grains-46e62865-1783335041588.webp"],
    deliveryOptions: ["Haulage"],
    farmerId: "2",
    farmerName: "Alhaji Musa Danjuma",
    farmerVerified: true,
    farmerTrustLevel: "Platinum",
  },
  {
    id: "p4",
    name: "Ofada Rice (Local Nigerian)",
    category: "Crops",
    description: "Premium unpolished Ofada rice, stone-free and highly nutritious.",
    quantity: 300,
    unit: "kg",
    price: 1800,
    harvestDate: "2024-03-15",
    location: "Abeokuta, Ogun",
    images: ["https://storage.googleapis.com/dala-prod-public-storage/generated-images/8d322e49-9a02-4b5b-82a4-475380de7bac/ofada-rice-1dcdb6b6-1783335039828.webp"],
    deliveryOptions: ["Delivery", "Pickup"],
    farmerId: "6",
    farmerName: "Segun Abraham",
    farmerVerified: true,
    farmerTrustLevel: "Silver",
  },
  {
    id: "p5",
    name: "Live Large Catfish",
    category: "Fishery",
    description: "Fresh live catfish from a healthy pond, average size 1.5kg - 2kg.",
    quantity: 150,
    unit: "kg",
    price: 1200,
    harvestDate: "2024-03-27",
    location: "Uyo, Akwa Ibom",
    images: ["https://storage.googleapis.com/dala-prod-public-storage/generated-images/8d322e49-9a02-4b5b-82a4-475380de7bac/live-catfish-aa89e684-1783335039176.webp"],
    deliveryOptions: ["Special Handling Delivery"],
    farmerId: "7",
    farmerName: "Dr. Ben Akpan",
    farmerVerified: false,
    farmerTrustLevel: "Bronze",
  },
  {
    id: "p6",
    name: "Broiler Chickens (Live)",
    category: "Poultry",
    description: "Healthy 8-week old broiler chickens, average weight 2.5kg.",
    quantity: 100,
    unit: "piece",
    price: 4500,
    harvestDate: "2024-03-26",
    location: "Abeokuta, Ogun",
    images: ["https://storage.googleapis.com/dala-prod-public-storage/generated-images/8d322e49-9a02-4b5b-82a4-475380de7bac/broiler-chickens-e65cd1b2-1783335039685.webp"],
    deliveryOptions: ["Special Handling Delivery", "Pickup"],
    farmerId: "6",
    farmerName: "Segun Abraham",
    farmerVerified: true,
    farmerTrustLevel: "Silver",
  },
  {
    id: "p7",
    name: "Fresh Farm Eggs (Crate)",
    category: "Poultry",
    description: "Crates of 30 fresh brown eggs, large size.",
    quantity: 50,
    unit: "dozen",
    price: 3800,
    harvestDate: "2024-03-27",
    location: "Abeokuta, Ogun",
    images: ["https://storage.googleapis.com/dala-prod-public-storage/generated-images/8d322e49-9a02-4b5b-82a4-475380de7bac/fresh-farm-eggs-433c758e-1783335041364.webp"],
    deliveryOptions: ["Pickup", "Local Delivery"],
    farmerId: "6",
    farmerName: "Segun Abraham",
    farmerVerified: true,
    farmerTrustLevel: "Silver",
  },
  {
    id: "p8",
    name: "Pure Red Palm Oil (4L)",
    category: "Processed",
    description: "Unadulterated red palm oil, processed in a clean environment.",
    quantity: 80,
    unit: "piece",
    price: 6500,
    harvestDate: "2024-03-10",
    location: "Owerri, Imo",
    images: ["https://storage.googleapis.com/dala-prod-public-storage/generated-images/8d322e49-9a02-4b5b-82a4-475380de7bac/red-palm-oil-b7079398-1783335040138.webp"],
    deliveryOptions: ["Delivery"],
    farmerId: "3",
    farmerName: "Mrs. Oluchi Nwosu",
    farmerVerified: true,
    farmerTrustLevel: "Gold",
  },
  {
    id: "p9",
    name: "Fine White Garri (50kg Bag)",
    category: "Processed",
    description: "Well-fried white garri, crunchy and dry.",
    quantity: 40,
    unit: "piece",
    price: 28000,
    harvestDate: "2024-03-24",
    location: "Ibadan, Oyo",
    images: ["https://storage.googleapis.com/dala-prod-public-storage/generated-images/8d322e49-9a02-4b5b-82a4-475380de7bac/white-garri-60a9a302-1783335041583.webp"],
    deliveryOptions: ["Haulage"],
    farmerId: "3",
    farmerName: "Mrs. Oluchi Nwosu",
    farmerVerified: true,
    farmerTrustLevel: "Gold",
  },
  {
    id: "p10",
    name: "Quality Cocoa Pods",
    category: "Crops",
    description: "High-grade cocoa pods for nursery or processing.",
    quantity: 100,
    unit: "piece",
    price: 200,
    harvestDate: "2024-03-18",
    location: "Akure, Ondo",
    images: ["https://storage.googleapis.com/dala-prod-public-storage/generated-images/8d322e49-9a02-4b5b-82a4-475380de7bac/cocoa-pods-6cba6fdf-1783335042546.webp"],
    deliveryOptions: ["Pickup"],
    farmerId: "2",
    farmerName: "Alhaji Musa Danjuma",
    farmerVerified: true,
    farmerTrustLevel: "Platinum",
  },
];

export const mockOrders: Order[] = [
  {
    id: "o1",
    buyerId: "4",
    items: [{ productId: "p3", quantity: 50, price: 450 }],
    total: 22500,
    status: "Delivered",
    deliveryAddress: "Block 4, Lekki Phase 1, Lagos",
    shippingCost: 2500,
    orderDate: "2024-03-15",
  },
  {
    id: "o2",
    buyerId: "5",
    items: [{ productId: "p8", quantity: 2, price: 6500 }],
    total: 13000,
    status: "Processing",
    deliveryAddress: "Plot 12, Gwarinpa, Abuja",
    shippingCost: 1500,
    orderDate: "2024-03-25",
  },
  {
    id: "o3",
    buyerId: "4",
    items: [{ productId: "p4", quantity: 10, price: 1800 }],
    total: 18000,
    status: "Shipped",
    deliveryAddress: "Victoria Island, Lagos",
    shippingCost: 1200,
    orderDate: "2024-03-20",
  },
];

export const revenueData = [
  { name: "Jan", revenue: 450000 },
  { name: "Feb", revenue: 380000 },
  { name: "Mar", revenue: 620000 },
  { name: "Apr", revenue: 540000 },
  { name: "May", revenue: 780000 },
  { name: "Jun", revenue: 690000 },
];

export const salesCategoryData = [
  { name: "Crops", value: 45 },
  { name: "Poultry", value: 25 },
  { name: "Fishery", value: 15 },
  { name: "Processed", value: 15 },
];
